### ISSUE TITLE
Zero IAT on the first DATA packet

### ISSUE THREAD

**Issue by maxsharabayko** [mbakholdina/srt-packet-iat#1]
The first DATA packet obviously has 0 IAT. But this value is included in statistical measurements.

![image](https://user-images.githubusercontent.com/12700120/68747665-4faeb000-05fb-11ea-9085-f7fb7eb12493.png)

Sample capture to reproduce:
[zeo_iat_sample.zip](https://github.com/mbakholdina/srt-packet-iat/files/3840203/zeo_iat_sample.zip)

```
python packet_iat.py --help zeo_iat_sample.pcapng --data
```

**Comment by mbakholdina** [comment]
Fixed within commit ff754f539247ca666f294c5cde923200d40722ee. There is a known [issue](https://github.com/mbakholdina/lib-tcpdump-processing/issues/2) however in [lib-tcpdump processing](https://github.com/mbakholdina/lib-tcpdump-processing) library: after timestamps adjustments done within the library two consecutive packets may have the same timestamps which also leads to zero packet inter-arrival time. Some additional timestamps adjustments might be required.
